#############################################################################
# Makefile for building: Netflix-
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Jan 22 03:01:11 2015
# Project:  Netflix-.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Netflix-.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Ilib -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.cpp \
		movieinfo_window.cpp \
		moviesearchwindow.cpp \
		netflix.cpp \
		newuserwindow.cpp \
		popupwindow.cpp \
		ratewindow.cpp \
		test.cpp moc_mainwindow.cpp \
		moc_movieinfo_window.cpp \
		moc_moviesearchwindow.cpp \
		moc_newuserwindow.cpp \
		moc_popupwindow.cpp \
		moc_ratewindow.cpp
OBJECTS       = mainwindow.o \
		movieinfo_window.o \
		moviesearchwindow.o \
		netflix.o \
		newuserwindow.o \
		popupwindow.o \
		ratewindow.o \
		test.o \
		moc_mainwindow.o \
		moc_movieinfo_window.o \
		moc_moviesearchwindow.o \
		moc_newuserwindow.o \
		moc_popupwindow.o \
		moc_ratewindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Netflix-.pro
QMAKE_TARGET  = Netflix-
DESTDIR       = 
TARGET        = Netflix-

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Netflix-.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Netflix-.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Netflix-.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Netflix-1.0.0 || $(MKDIR) .tmp/Netflix-1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Netflix-1.0.0/ && $(COPY_FILE) --parents mainwindow.h Mergesort.h movie.h movieinfo_window.h moviesearchwindow.h netflix.h newuserwindow.h popupwindow.h ratewindow.h user.h lib/hash.h lib/hashimpl.h lib/map.h lib/mapimpl.h lib/queue.h lib/queueimpl.h lib/set.h lib/setimpl.h mergesort/Mergesort.h movie.cpp user.cpp .tmp/Netflix-1.0.0/ && $(COPY_FILE) --parents mainwindow.cpp movieinfo_window.cpp moviesearchwindow.cpp netflix.cpp newuserwindow.cpp popupwindow.cpp ratewindow.cpp test.cpp .tmp/Netflix-1.0.0/ && (cd `dirname .tmp/Netflix-1.0.0` && $(TAR) Netflix-1.0.0.tar Netflix-1.0.0 && $(COMPRESS) Netflix-1.0.0.tar) && $(MOVE) `dirname .tmp/Netflix-1.0.0`/Netflix-1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Netflix-1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_movieinfo_window.cpp moc_moviesearchwindow.cpp moc_newuserwindow.cpp moc_popupwindow.cpp moc_ratewindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_movieinfo_window.cpp moc_moviesearchwindow.cpp moc_newuserwindow.cpp moc_popupwindow.cpp moc_ratewindow.cpp
moc_mainwindow.cpp: netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_movieinfo_window.cpp: netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		movieinfo_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) movieinfo_window.h -o moc_movieinfo_window.cpp

moc_moviesearchwindow.cpp: movieinfo_window.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		ratewindow.h \
		popupwindow.h \
		mainwindow.h \
		moviesearchwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) moviesearchwindow.h -o moc_moviesearchwindow.cpp

moc_newuserwindow.cpp: mainwindow.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		newuserwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) newuserwindow.h -o moc_newuserwindow.cpp

moc_popupwindow.cpp: netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		ratewindow.h \
		popupwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) popupwindow.h -o moc_popupwindow.cpp

moc_ratewindow.cpp: netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		ratewindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ratewindow.h -o moc_ratewindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

mainwindow.o: mainwindow.cpp mainwindow.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		newuserwindow.h \
		moviesearchwindow.h \
		movieinfo_window.h \
		ratewindow.h \
		popupwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

movieinfo_window.o: movieinfo_window.cpp mainwindow.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		newuserwindow.h \
		moviesearchwindow.h \
		movieinfo_window.h \
		ratewindow.h \
		popupwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movieinfo_window.o movieinfo_window.cpp

moviesearchwindow.o: moviesearchwindow.cpp mainwindow.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		newuserwindow.h \
		moviesearchwindow.h \
		movieinfo_window.h \
		ratewindow.h \
		popupwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moviesearchwindow.o moviesearchwindow.cpp

netflix.o: netflix.cpp netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		movie.cpp \
		user.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netflix.o netflix.cpp

newuserwindow.o: newuserwindow.cpp newuserwindow.h \
		mainwindow.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newuserwindow.o newuserwindow.cpp

popupwindow.o: popupwindow.cpp ratewindow.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		mainwindow.h \
		newuserwindow.h \
		moviesearchwindow.h \
		movieinfo_window.h \
		popupwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o popupwindow.o popupwindow.cpp

ratewindow.o: ratewindow.cpp ratewindow.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h \
		mainwindow.h \
		newuserwindow.h \
		moviesearchwindow.h \
		movieinfo_window.h \
		popupwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ratewindow.o ratewindow.cpp

test.o: test.cpp mainwindow.h \
		netflix.h \
		lib/map.h \
		lib/mapimpl.h \
		lib/set.h \
		lib/setimpl.h \
		movie.h \
		lib/hash.h \
		lib/hashimpl.h \
		user.h \
		lib/queue.h \
		lib/queueimpl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_movieinfo_window.o: moc_movieinfo_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_movieinfo_window.o moc_movieinfo_window.cpp

moc_moviesearchwindow.o: moc_moviesearchwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moviesearchwindow.o moc_moviesearchwindow.cpp

moc_newuserwindow.o: moc_newuserwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newuserwindow.o moc_newuserwindow.cpp

moc_popupwindow.o: moc_popupwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_popupwindow.o moc_popupwindow.cpp

moc_ratewindow.o: moc_ratewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ratewindow.o moc_ratewindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

